import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#4f3e00",
        "inverse-surface": "#e0e3e5",
        "on-surface-variant": "#c4c6ce",
        "surface": "#101415",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "secondary": "#a5c8ff",
        "surface-bright": "#363a3b",
        "inverse-on-surface": "#2d3133",
        "on-primary": "#1d314d",
        "on-secondary-fixed": "#001c3a",
        "inverse-primary": "#4c5f7e",
        "on-secondary": "#00315e",
        "deep-ocean": "#051324",
        "surface-tint": "#b3c8ea",
        "surface-dim": "#101415",
        "error-container": "#93000a",
        "background": "#101415",
        "tertiary-fixed-dim": "#e9c349",
        "outline-variant": "#44474d",
        "on-surface": "#e0e3e5",
        "primary": "#b3c8ea",
        "on-tertiary": "#3c2f00",
        "tertiary-fixed": "#ffe088",
        "outline": "#8e9198",
        "secondary-fixed": "#d4e3ff",
        "surface-container": "#1d2022",
        "secondary-fixed-dim": "#a5c8ff",
        "primary-container": "#081f3a",
        "on-primary-container": "#7487a8",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#b3c8ea",
        "nautical-silver": "#E2E8F0",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#004785",
        "gold-leaf": "#D4AF37",
        "on-tertiary-fixed": "#241a00",
        "secondary-container": "#024a89",
        "on-primary-fixed": "#051c37",
        "tertiary-container": "#cca830",
        "on-background": "#e0e3e5",
        "surface-container-high": "#272a2c",
        "surface-container-lowest": "#0b0f10",
        "on-secondary-container": "#8bbbff",
        "surface-container-low": "#191c1e",
        "on-primary-fixed-variant": "#344865",
        "tertiary": "#eac349",
        "surface-variant": "#323537",
        "surface-container-highest": "#323537",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Hanken Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        shipSlide: {
          from: { transform: "translateX(-100%) translateY(0)" },
          to: { transform: "translateX(200%) translateY(2px)" },
        },
        wave: {
          "0%": { transform: "translateX(0)" },
          "50%": { transform: "translateX(-25%)" },
          "100%": { transform: "translateX(0)" },
        },
        rotateGlobe: {
          from: { transform: "rotateY(0deg)" },
          to: { transform: "rotateY(360deg)" },
        },
        urgentPulse: {
          "0%": { boxShadow: "0 0 0 0 rgba(212, 175, 55, 0.4)" },
          "70%": { boxShadow: "0 0 0 6px rgba(212, 175, 55, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(212, 175, 55, 0)" },
        },
        pulseGold: {
          "0%": { boxShadow: "0 0 0 0 rgba(212, 175, 55, 0.4)" },
          "70%": { boxShadow: "0 0 0 15px rgba(212, 175, 55, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(212, 175, 55, 0)" },
        },
        successPop: {
          "0%": { transform: "scale(0.8)", opacity: "0" },
          "50%": { transform: "scale(1.2)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        sheen: {
          "0%": { left: "-50%" },
          "100%": { left: "100%" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        ship: "shipSlide 60s linear infinite",
        wave: "wave 15s ease-in-out infinite",
        globe: "rotateGlobe 40s linear infinite",
        urgent: "urgentPulse 2s infinite",
        "pulse-gold": "pulseGold 2s infinite",
        "success-pop": "successPop 0.5s forwards ease-out",
        "fade-in-up": "fadeInUp 0.8s cubic-bezier(0.2, 0.8, 0.2, 1) forwards",
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
};

export default config;
